baseURL = "https://rigille.github.io"
languageCode = "pt-br"
title = "dessages"
theme = "hugo-theme-codex"
disqusShortname = "rigille"

[params]
twitter = "https://twitter.com/impression28"
github = "https://github.com/impression28"
iconOrder = ["GitHub", "Twitter"]

[[menu.main]]
identifier = "sobre"
name = "sobre"
title = "sobre"
url = "/"

[[menu.main]]
identifier = "blog"
name = "blog"
title = "blog"
url = "/blog"

[[menu.main]]
identifier = "exercicios"
name = "exercicios"
title = "exercicios"
url = "/exercicios"

[[menu.main]]
identifier = "guia"
name = "guia"
title = "guia"
url = "/guia"

[params.colors]
fancy = "#ffaa00"
